provider "aws" {
  region = "us-east-1"
}

variable "ami_id" {
  description = "The AMI ID generated by Packer"
  type        = string
}

resource "aws_security_group" "allow_http" {
  name        = "allow_http_no_ssh"
  description = "Allow HTTP inbound traffic and all outbound"

  ingress {
    description = "HTTP from anywhere"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_http_no_ssh"
  }
}

resource "aws_instance" "web" {
  ami                  = var.ami_id
  instance_type        = "t3.micro"
  iam_instance_profile = aws_iam_instance_profile.awx_ssm_profile.name
  security_groups      = [aws_security_group.allow_http.name]

  tags = {
    Name    = "ZeroTrustWebServer"
    Project = "ZeroTrust"
  }
}

resource "random_id" "bucket_suffix" {
  byte_length = 8
}

resource "aws_s3_bucket" "ansible_ssm_bucket" {
  bucket = "ansible-ssm-transfer-${random_id.bucket_suffix.hex}"

  tags = {
    Name    = "AnsibleSSMTransfer"
    Project = "ZeroTrust"
  }
}
