apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-layer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vijaymanda06/homelab-fleet.git
    targetRevision: HEAD
    path: infrastructure  # <-- Points to root infrastructure folder
    directory:
      recurse: true  # Recurse to include core/, cert-manager/, and other subdirectories
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Apps usually live in argocd namespace, resources will go to their own ns defined in manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
