apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vijaymanda06/homelab-fleet.git
    targetRevision: HEAD
    path: infrastructure/monitoring  # <-- Points to your monitoring folder
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # --- THIS IS THE PATCH WE NEEDED ---
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: monitoring-grafana
      jsonPointers:
        - /spec/volumeName
